name: slurp
version: 0.0.0

category: Distribution
description: Slurp is an example implementation of the SLURP proposal.
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: A single liberal unified registry of Haskell packages.

executable:
  dependencies:
    - aeson >= 1.2.3 && < 1.3
    - base >= 4.10.1 && < 4.11
    - bytestring >= 0.10.8 && < 0.11
    - Cabal >= 2.0.1 && < 2.1
    - containers >= 0.5.10 && < 0.6
    - http-types >= 0.9.1 && < 0.10
    - network-uri >= 2.6.1 && < 2.7
    - stm >= 2.4.4 && < 2.5
    - text >= 1.2.2 && < 1.3
    - wai >= 3.2.1 && < 3.3
    - warp >= 3.2.13 && < 3.3
  ghc-options:
    - -rtsopts
    - -threaded
    - -Weverything
    - -Wno-implicit-prelude
    - -Wno-safe
    - -Wno-unsafe
  main: slurp.hs
